<?php

use Illuminate\Database\Seeder;

class GprsPackagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $thumbs = array (
            [
                'name'=>'Data Package 1',
                'zone_id'=>1,
                'code'=>13,
                'duration'=>1,
                'data'=>10,
                'price'=>0.50,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 2',
                'zone_id'=>1,
                'code'=>14,
                'duration'=>1,
                'data'=>50,
                'price'=>2.50,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 3',
                'zone_id'=>1,
                'code'=>15,
                'duration'=>7,
                'data'=>150,
                'price'=>5.50,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 4',
                'zone_id'=>1,
                'code'=>16,
                'duration'=>14,
                'data'=>250,
                'price'=>8.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 5',
                'zone_id'=>1,
                'code'=>17,
                'duration'=>30,
                'data'=>500,
                'price'=>12.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 6',
                'zone_id'=>1,
                'code'=>18,
                'duration'=>30,
                'data'=>1000,
                'price'=>18.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 7',
                'zone_id'=>1,
                'code'=>19,
                'duration'=>30,
                'data'=>2000,
                'price'=>34.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 1',
                'zone_id'=>2,
                'code'=>21,
                'duration'=>1,
                'data'=>10,
                'price'=>1.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 2',
                'zone_id'=>2,
                'code'=>22,
                'duration'=>1,
                'data'=>50,
                'price'=>3.50,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 3',
                'zone_id'=>2,
                'code'=>23,
                'duration'=>7,
                'data'=>150,
                'price'=>9.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 4',
                'zone_id'=>2,
                'code'=>24,
                'duration'=>14,
                'data'=>250,
                'price'=>14.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 5',
                'zone_id'=>2,
                'code'=>25,
                'duration'=>30,
                'data'=>500,
                'price'=>26.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 6',
                'zone_id'=>2,
                'code'=>26,
                'duration'=>30,
                'data'=>1000,
                'price'=>49.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 7',
                'zone_id'=>2,
                'code'=>27,
                'duration'=>30,
                'data'=>2000,
                'price'=>89.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 1',
                'zone_id'=>3,
                'code'=>29,
                'duration'=>1,
                'data'=>10,
                'price'=>1.40,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 2',
                'zone_id'=>3,
                'code'=>30,
                'duration'=>1,
                'data'=>50,
                'price'=>5.50,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 3',
                'zone_id'=>3,
                'code'=>31,
                'duration'=>7,
                'data'=>150,
                'price'=>15.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 4',
                'zone_id'=>3,
                'code'=>32,
                'duration'=>14,
                'data'=>250,
                'price'=>24.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 5',
                'zone_id'=>3,
                'code'=>33,
                'duration'=>30,
                'data'=>500,
                'price'=>45.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 6',
                'zone_id'=>3,
                'code'=>34,
                'duration'=>30,
                'data'=>1000,
                'price'=>89.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
            [
                'name'=>'Data Package 7',
                'zone_id'=>3,
                'code'=>35,
                'duration'=>30,
                'data'=>2000,
                'price'=>169.00,
                "created_at" => \Carbon\Carbon::now(),
				"updated_at" => \Carbon\Carbon::now(),
            ],
        );

		$db = DB::table('gprs_packages')->insert($thumbs);
    }
}
